<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Hint' => 'Подсказка',
    'Actually, this block shows:' => 'На самом деле этот блок показывает:',
    'Admin panel' => 'Админка',
    'Demo blog for yii2-multilingual' => 'Демонстрационный блог для yii2-multilingual',
    'EN only post' => 'Английский пост',
    'Email' => '',
    'Hi! There\'s new post on yii2-multilingual-demo' => 'Привет! Появился новый пост на yii2-multilingual-demo',
    'How console command will send letter in users language' => 'Как консольная комманда будет отсылать письма с учетом языка пользователя',
    'How excludeRoutes param works and how to determine users language without URL info' => 'Как работает параметр excludeRoutes и определение языка без информации в URL',
    'How to add tasks to yii2-deferred-tasks' => 'Как ставить задачи в yii2-deferred-tasks',
    'ID' => '',
    'Image Src' => '',
    'Language ID' => '',
    'Login' => 'Войти',
    'Model ID' => '',
    'Multilingual post' => 'Многоязычный пост',
    'Object has been deleted.' => 'Объект был удален',
    'Object saved.' => 'Объект сохранён.',
    'Page edit' => 'Редактирование страницы',
    'Pages' => 'Страницы',
    'Photo' => 'Фото',
    'Post edit' => 'Редактирование записи',
    'Posts' => 'Записи',
    'RU only post' => 'Русский пост',
    'Sort Order' => '',
    'Subscribed At' => '',
    'This is an example application showing main package features.' => 'Это приложение-пример для показа основных функций пакета.',
    'Unpublished posts translations are not be displayed in listings till they become published.' => 'Неопубликованные переводы записей не появляются в листингах, пока не станут опубликованными.',
    'Updated At' => '',
    'You can switch languages in top menu' => 'Вы можете переключать языки в меню',
    'Add' => 'Добавить',
    'Announce' => 'Анонс',
    'Comments' => 'Комментарии',
    'Content' => 'Контент',
    'Created At' => 'Дата публикации',
    'Current photo' => 'Текущее фото',
    'Description' => 'Описание',
    'Get the <i>latest news</i> and <i>updates</i> from the website' => 'Получайте <i>последние новости</i> и <i>обновления</i> с сайта.',
    'Home' => 'Главная',
    'Is Active' => 'Публиковать',
    'Newsletter' => 'Рассылка',
    'Read more' => 'Читать далее',
    'Save' => 'Сохранить',
    'Share with Facebook' => 'Поделиться с помощью Facebook',
    'Share with Google+' => 'Поделиться с помощью Google+',
    'Share with OK.ru' => 'Поделиться с помощью Одноклассники.ru',
    'Share with Pinterest' => 'Поделиться с помощью Pinterest',
    'Share with Twitter' => 'Поделиться с помощью Twitter',
    'Share with VK' => 'Поделиться с помощью VK',
    'Share:' => 'Поделиться:',
    'Subscribe' => 'Подписаться',
    'Title' => 'Заголовок',
    'View comments' => 'Показать комментарии',
];
